export type CytocareTest = {
  id: string;
  category: string;
  name: string;
  vial: string;
  price: number;
  reportingTime: string;
  sourcePage: number;
};

export const cytocareTests: CytocareTest[] = [
  {
  id: "basic-metabolic-panel-599",
  category: "Cytocare Profiles & Panels",
  name: "Basic Metabolic Panel",
  vial: "RED, PURPLE, GREY, URINE",
  price: 599,
  reportingTime: "Same day",
  sourcePage: 0,
},

    {
    id: "men-under-30-health-package",
    category: "Routine Health Checkups",
    name: "Men Under 30 Health Package",
    vial: "RED, PURPLE, GREY, URINE",
    price: 1699,
    reportingTime: "Same day / As per test schedule",
    sourcePage: 0,
  },
  {
    id: "men-30-45-health-package",
    category: "Routine Health Checkups",
    name: "Men 30-45 Health Package",
    vial: "RED, PURPLE, GREY, URINE",
    price: 2499,
    reportingTime: "Same day / As per test schedule",
    sourcePage: 0,
  },
  {
    id: "men-45-60-health-package",
    category: "Routine Health Checkups",
    name: "Men 45-60 Health Package",
    vial: "RED, PURPLE, GREY, URINE",
    price: 3499,
    reportingTime: "Same day / As per test schedule",
    sourcePage: 0,
  },
  {
    id: "men-above-60-health-package",
    category: "Routine Health Checkups",
    name: "Men Above 60 Health Package",
    vial: "RED, PURPLE, GREY, URINE",
    price: 3599,
    reportingTime: "Same day / As per test schedule",
    sourcePage: 0,
  },
  {
    id: "women-under-30-health-package",
    category: "Routine Health Checkups",
    name: "Women Under 30 Health Package",
    vial: "RED, PURPLE, GREY, URINE",
    price: 699,
    reportingTime: "Same day / As per test schedule",
    sourcePage: 0,
  },
  {
    id: "women-30-45-health-package",
    category: "Routine Health Checkups",
    name: "Women 30-45 Health Package",
    vial: "RED, PURPLE, GREY, URINE",
    price: 1699,
    reportingTime: "Same day / As per test schedule",
    sourcePage: 0,
  },
  {
    id: "women-45-60-health-package",
    category: "Routine Health Checkups",
    name: "Women 45-60 Health Package",
    vial: "RED, PURPLE, GREY, URINE",
    price: 3499,
    reportingTime: "Same day / As per test schedule",
    sourcePage: 0,
  },
  {
    id: "women-above-60-health-package",
    category: "Routine Health Checkups",
    name: "Women Above 60 Health Package",
    vial: "RED, PURPLE, GREY, URINE",
    price: 3799,
    reportingTime: "Same day / As per test schedule",
    sourcePage: 0,
  },
  {
    id: "abo-rh-blood-grouping-001",
    category: "Hematology",
    name: "ABO & RH (BLOOD GROUPING)",
    vial: "PURPLE - EDTA",
    price: 99,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "bt-ct-002",
    category: "Hematology",
    name: "BT CT",
    vial: "",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "cbc-complete-blood-counts-003",
    category: "Hematology",
    name: "CBC - COMPLETE BLOOD COUNTS",
    vial: "PURPLE - EDTA",
    price: 299,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "cbc-esr-hemograme-004",
    category: "Hematology",
    name: "CBC + ESR - HEMOGRAME",
    vial: "PURPLE - EDTA",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "pbs-peripheral-blood-smear-comments-005",
    category: "Hematology",
    name: "PBS - (Peripheral blood Smear) - Comments",
    vial: "PURPLE - EDTA",
    price: 499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "esr-006",
    category: "Hematology",
    name: "ESR",
    vial: "BLACK",
    price: 99,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "hemoglobin-hb-007",
    category: "Hematology",
    name: "HEMOGLOBIN (HB%)",
    vial: "PURPLE - EDTA",
    price: 99,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "malaria-parasite-peripheral-smear-bsmp-008",
    category: "Hematology",
    name: "MALARIA PARASITE (PERIPHERAL SMEAR) - BSMP",
    vial: "PURPLE - EDTA",
    price: 299,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "malaria-card-antigen-test-009",
    category: "Hematology",
    name: "MALARIA CARD ANTIGEN TEST",
    vial: "PURPLE - EDTA",
    price: 299,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "sickling-test-010",
    category: "Hematology",
    name: "SICKLING TEST",
    vial: "PURPLE - EDTA",
    price: 399,
    reportingTime: "48 hrs",
    sourcePage: 1,
  },
  {
    id: "platelet-count-011",
    category: "Hematology",
    name: "PLATELET COUNT",
    vial: "PURPLE - EDTA",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "prothrombin-time-with-inr-pt-inr-012",
    category: "Hematology",
    name: "PROTHROMBIN TIME WITH INR (PT INR)",
    vial: "SKY",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "aptt-plasma-013",
    category: "Hematology",
    name: "APTT, PLASMA",
    vial: "SKY",
    price: 499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "reticulocyte-count-014",
    category: "Hematology",
    name: "RETICULOCYTE COUNT",
    vial: "PURPLE - EDTA",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "aso-anti-streptolysin-o-quantitative-015",
    category: "Serology",
    name: "ASO (ANTI STREPTOLYSIN O) - QUANTITATIVE",
    vial: "RED - PLAIN",
    price: 449,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "crp-c-reactive-protein-quantitative-016",
    category: "Serology",
    name: "CRP (C-REACTIVE PROTEIN) - QUANTITATIVE",
    vial: "RED - PLAIN",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "ra-factor-quantitative-017",
    category: "Serology",
    name: "RA FACTOR - QUANTITATIVE",
    vial: "RED - PLAIN",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "chikungunya-card-test-rapid-018",
    category: "Serology",
    name: "CHIKUNGUNYA CARD TEST (RAPID)",
    vial: "RED - PLAIN",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "dengue-card-test-ns1-igg-igm-019",
    category: "Serology",
    name: "DENGUE CARD TEST (NS1 + IGG + IGM)",
    vial: "RED - PLAIN",
    price: 799,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "hiv-i-ii-card-test-020",
    category: "Serology",
    name: "HIV I & II Card Test",
    vial: "RED - PLAIN",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "hbsag-australia-antigen-card-test-021",
    category: "Serology",
    name: "HBSAG (AUSTRALIA ANTIGEN) Card Test",
    vial: "RED - PLAIN",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "hcv-hepatitis-c-antibody-card-test-022",
    category: "Serology",
    name: "HCV (HEPATITIS C ANTIBODY) Card Test",
    vial: "RED - PLAIN",
    price: 449,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "hbsag-elisa-method-023",
    category: "Serology",
    name: "HBSAG - ELISA Method",
    vial: "RED - PLAIN",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "hiv-i-ii-elisa-method-024",
    category: "Serology",
    name: "HIV I & II - ELISA Method",
    vial: "RED - PLAIN",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "hcv-elisa-method-025",
    category: "Serology",
    name: "HCV - ELISA Method",
    vial: "RED - PLAIN",
    price: 799,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "mantoux-tuberculin-test-026",
    category: "Serology",
    name: "MANTOUX (TUBERCULIN TEST)",
    vial: "10 TU / 5 TU",
    price: 199,
    reportingTime: "48 to 72 Hrs",
    sourcePage: 1,
  },
  {
    id: "microfilaria-card-test-027",
    category: "Serology",
    name: "MICROFILARIA CARD TEST",
    vial: "PURPLE / RED",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "microfilaria-antigen-elisa-method-028",
    category: "Serology",
    name: "MICROFILARIA ANTIGEN - ELISA Method",
    vial: "PURPLE / RED",
    price: 1499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "h-pylori-card-test-029",
    category: "Serology",
    name: "H PYLORI CARD TEST",
    vial: "RED - PLAIN",
    price: 799,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "h-pylori-igg-iga-test-030",
    category: "Serology",
    name: "H PYLORI IGG IGA TEST",
    vial: "RED - PLAIN",
    price: 2499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "vdrl-test-031",
    category: "Serology",
    name: "VDRL TEST",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "typhi-dot-igg-igm-032",
    category: "Serology",
    name: "TYPHI DOT IGG IGM",
    vial: "RED - PLAIN",
    price: 499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "widal-test-033",
    category: "Serology",
    name: "WIDAL TEST",
    vial: "RED - PLAIN",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "stool-routine-examination-034",
    category: "Clinical Pathology",
    name: "STOOL ROUTINE EXAMINATION",
    vial: "CONTAINER",
    price: 299,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "stool-for-occult-blood-035",
    category: "Clinical Pathology",
    name: "STOOL FOR OCCULT BLOOD",
    vial: "CONTAINER",
    price: 299,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "semen-analysis-colletion-at-lab-only-036",
    category: "Clinical Pathology",
    name: "SEMEN ANALYSIS - Colletion at Lab Only",
    vial: "CONTAINER",
    price: 299,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-bile-salt-pigment-037",
    category: "Clinical Pathology",
    name: "URINE BILE SALT / PIGMENT",
    vial: "CONTAINER",
    price: 99,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-for-ketone-bodies-038",
    category: "Clinical Pathology",
    name: "URINE FOR KETONE BODIES",
    vial: "CONTAINER",
    price: 99,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-pregnancy-test-039",
    category: "Clinical Pathology",
    name: "URINE PREGNANCY TEST",
    vial: "CONTAINER",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-routine-examination-040",
    category: "Clinical Pathology",
    name: "URINE ROUTINE EXAMINATION",
    vial: "CONTAINER",
    price: 99,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-culture-susceptibility-041",
    category: "Clinical Pathology",
    name: "URINE CULTURE & SUSCEPTIBILITY",
    vial: "CONTAINER",
    price: 399,
    reportingTime: "48 Hrs",
    sourcePage: 1,
  },
  {
    id: "urine-r-e-c-s-042",
    category: "Clinical Pathology",
    name: "URINE R/E & C/S",
    vial: "CONTAINER",
    price: 499,
    reportingTime: "48 Hrs",
    sourcePage: 1,
  },
  {
    id: "urine-sugar-043",
    category: "Clinical Pathology",
    name: "URINE SUGAR",
    vial: "CONTAINER",
    price: 99,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-protein-24-hrs-044",
    category: "Clinical Pathology",
    name: "URINE PROTEIN 24 HRS",
    vial: "CONTAINER",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-24-hrs-for-acid-fast-bacilli-045",
    category: "Clinical Pathology",
    name: "URINE 24 HRS FOR ACID FAST BACILLI",
    vial: "CONTAINER",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-albumin-microalbumin-a-c-ratio-spot-046",
    category: "Clinical Pathology",
    name: "URINE ALBUMIN / MICROALBUMIN A/C RATIO-SPOT",
    vial: "CONTAINER",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-protein-047",
    category: "Clinical Pathology",
    name: "URINE PROTEIN",
    vial: "CONTAINER",
    price: 99,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 1,
  },
  {
    id: "urine-protein-creatinine-ratio-spot-24-hrs-048",
    category: "Clinical Pathology",
    name: "URINE PROTEIN CREATININE RATIO (SPOT / 24 HRS)",
    vial: "CONTAINER",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "ada-adenosine-deaminase-049",
    category: "Biochemistry",
    name: "ADA - Adenosine Deaminase",
    vial: "RED - PLAIN",
    price: 899,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "alkaline-phosphatase-serum-050",
    category: "Biochemistry",
    name: "ALKALINE PHOSPHATASE, SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "albumin-serum-051",
    category: "Biochemistry",
    name: "ALBUMIN, SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "amylase-serum-052",
    category: "Biochemistry",
    name: "AMYLASE, SERUM",
    vial: "RED - PLAIN",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "bilirubin-total-serum-053",
    category: "Biochemistry",
    name: "BILIRUBIN (TOTAL), SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "bilirubin-total-direct-indirect-serum-054",
    category: "Biochemistry",
    name: "BILIRUBIN (TOTAL, DIRECT & INDIRECT), SERUM",
    vial: "RED - PLAIN",
    price: 299,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "calcium-serum-055",
    category: "Biochemistry",
    name: "CALCIUM, SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "cholesterol-total-serum-056",
    category: "Biochemistry",
    name: "CHOLESTEROL (TOTAL), SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "cpk-057",
    category: "Biochemistry",
    name: "CPK",
    vial: "RED - PLAIN",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "ck-mb-058",
    category: "Biochemistry",
    name: "CK MB",
    vial: "RED - PLAIN",
    price: 799,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "creatinine-serum-059",
    category: "Biochemistry",
    name: "CREATININE, SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "gamma-gt-ggt-060",
    category: "Biochemistry",
    name: "GAMMA GT (GGT)",
    vial: "RED - PLAIN",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "sugar-glucose-fasting-061",
    category: "Biochemistry",
    name: "SUGAR GLUCOSE FASTING",
    vial: "GREY - Fluoride",
    price: 49,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "sugar-glucose-pp-062",
    category: "Biochemistry",
    name: "SUGAR GLUCOSE PP",
    vial: "GREY - Fluoride",
    price: 49,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "sugar-glucose-random-063",
    category: "Biochemistry",
    name: "SUGAR GLUCOSE RANDOM",
    vial: "GREY - Fluoride",
    price: 49,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "egfr-glomerular-filtration-rate-064",
    category: "Biochemistry",
    name: "EGFR - GLOMERULAR FILTRATION RATE",
    vial: "RED - PLAIN",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "hba1c-glycosylated-heamoglobin-065",
    category: "Biochemistry",
    name: "HBA1C (GLYCOSYLATED HEAMOGLOBIN)",
    vial: "PURPLE",
    price: 499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "ldh-066",
    category: "Biochemistry",
    name: "LDH",
    vial: "RED - PLAIN",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "kft-1-kidney-function-test-creat-urea-calcium-uric-acid-067",
    category: "Biochemistry",
    name: "KFT-1 - KIDNEY FUNCTION TEST (creat, urea, calcium, uric acid)",
    vial: "RED",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "kft-2-kidney-function-test-with-electrolyte-urine-r-e-068",
    category: "Biochemistry",
    name: "KFT-2 - KIDNEY FUNCTION TEST with Electrolyte & Urine R/E",
    vial: "RED & Urine",
    price: 899,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "liver-function-test-lft-069",
    category: "Biochemistry",
    name: "LIVER FUNCTION TEST (LFT)",
    vial: "RED - PLAIN",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "lipid-profile-serum-070",
    category: "Biochemistry",
    name: "LIPID PROFILE,SERUM",
    vial: "RED - PLAIN",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "lipase-serum-071",
    category: "Biochemistry",
    name: "LIPASE, SERUM",
    vial: "RED - PLAIN",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "iron-serum-072",
    category: "Biochemistry",
    name: "IRON, SERUM",
    vial: "RED - PLAIN",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "phosphorus-serum-073",
    category: "Biochemistry",
    name: "PHOSPHORUS,SERUM",
    vial: "RED - PLAIN",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "total-protein-serum-074",
    category: "Biochemistry",
    name: "TOTAL PROTEIN, SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "potassium-k-serum-075",
    category: "Biochemistry",
    name: "POTASSIUM (K+), SERUM",
    vial: "RED - PLAIN",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "sodium-na-serum-076",
    category: "Biochemistry",
    name: "SODIUM (NA+), SERUM",
    vial: "RED - PLAIN",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "electrolytes-serum-077",
    category: "Biochemistry",
    name: "ELECTROLYTES, SERUM",
    vial: "RED - PLAIN",
    price: 399,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "protein-albumin-globulin-a-g-ratio-078",
    category: "Biochemistry",
    name: "PROTEIN, ALBUMIN, GLOBULIN A-G RATIO",
    vial: "RED - PLAIN",
    price: 499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "sgpt-serum-alt-079",
    category: "Biochemistry",
    name: "SGPT, SERUM - ALT",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "sgot-serum-ast-080",
    category: "Biochemistry",
    name: "SGOT, SERUM - AST",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "triglycerides-serum-081",
    category: "Biochemistry",
    name: "TRIGLYCERIDES, SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "urea-082",
    category: "Biochemistry",
    name: "UREA",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "uric-acid-serum-083",
    category: "Biochemistry",
    name: "URIC ACID, SERUM",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "t3-084",
    category: "Hormones & Tumor Marker",
    name: "T3",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "t4-085",
    category: "Hormones & Tumor Marker",
    name: "T4",
    vial: "RED - PLAIN",
    price: 149,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "tsh-086",
    category: "Hormones & Tumor Marker",
    name: "TSH",
    vial: "RED - PLAIN",
    price: 299,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "t3-t4-tsh-thyroid-profile-087",
    category: "Hormones & Tumor Marker",
    name: "T3 T4 TSH (THYROID PROFILE)",
    vial: "RED - PLAIN",
    price: 499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "ft3-ft4-tsh-088",
    category: "Hormones & Tumor Marker",
    name: "FT3, FT4, TSH",
    vial: "RED - PLAIN",
    price: 599,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "ft4-tsh-089",
    category: "Hormones & Tumor Marker",
    name: "FT4, TSH",
    vial: "RED - PLAIN",
    price: 499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "ft3-free-t3-090",
    category: "Hormones & Tumor Marker",
    name: "FT3 - FREE T3",
    vial: "RED - PLAIN",
    price: 249,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "ft4-free-t4-091",
    category: "Hormones & Tumor Marker",
    name: "FT4 - FREE T4",
    vial: "RED - PLAIN",
    price: 249,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 2,
  },
  {
    id: "beta-hcg-total-history-or-lmp-date-required-or-dr-s-prescription-092",
    category: "Hormones & Tumor Marker",
    name: "BETA HCG TOTAL - (History or LMP Date Required or Dr's Prescription)",
    vial: "RED - PLAIN",
    price: 799,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "lh-luteinising-hormone-093",
    category: "Hormones & Tumor Marker",
    name: "LH (LUTEINISING HORMONE)",
    vial: "RED - PLAIN",
    price: 449,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 3,
  },
  {
    id: "fsh-follicular-stimulating-hormone-094",
    category: "Hormones & Tumor Marker",
    name: "FSH (FOLLICULAR STIMULATING HORMONE)",
    vial: "RED - PLAIN",
    price: 449,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 3,
  },
  {
    id: "prl-prolactine-serum-history-required-095",
    category: "Hormones & Tumor Marker",
    name: "PRL (PROLACTINE), SERUM (History Required)",
    vial: "RED - PLAIN",
    price: 499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 3,
  },
  {
    id: "psa-total-prostate-specific-antigen-096",
    category: "Hormones & Tumor Marker",
    name: "PSA (TOTAL), PROSTATE SPECIFIC ANTIGEN",
    vial: "RED - PLAIN",
    price: 699,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "vitamin-d-25-hydroxy-097",
    category: "Hormones & Tumor Marker",
    name: "VITAMIN D (25 HYDROXY)",
    vial: "RED & PURPLE",
    price: 999,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "vitamin-b12-098",
    category: "Hormones & Tumor Marker",
    name: "VITAMIN B12",
    vial: "RED & PURPLE",
    price: 799,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "total-ige-serum-099",
    category: "Hormones & Tumor Marker",
    name: "TOTAL IGE, SERUM",
    vial: "RED - PLAIN",
    price: 799,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 3,
  },
  {
    id: "ferritin-serum-100",
    category: "Hormones & Tumor Marker",
    name: "FERRITIN, SERUM",
    vial: "RED - PLAIN",
    price: 799,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "pap-smear-101",
    category: "Cytology",
    name: "PAP SMEAR",
    vial: "CONTAINER",
    price: 599,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "lbc-liquid-based-cytology-102",
    category: "Cytology",
    name: "LBC-Liquid Based Cytology",
    vial: "CONTAINER",
    price: 1199,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "fluid-routine-examination-103",
    category: "Cytology",
    name: "FLUID ROUTINE EXAMINATION",
    vial: "CONTAINER",
    price: 799,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "fluid-cytology-104",
    category: "Cytology",
    name: "FLUID CYTOLOGY",
    vial: "CONTAINER",
    price: 799,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "fluid-analysis-with-ldh-afb-gram-ada-routine-and-cyto-105",
    category: "Cytology",
    name: "FLUID ANALYSIS (with LDH, AFB, GRAM, ADA, ROUTINE AND CYTO)",
    vial: "CONTAINER",
    price: 2799,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "bone-marrow-examination-106",
    category: "Cytology",
    name: "BONE MARROW EXAMINATION",
    vial: "In Lab only",
    price: 1499,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "fnac-fine-needle-aspiration-cytology-non-gynaec-cytology-107",
    category: "Cytology",
    name: "FNAC - FINE NEEDLE ASPIRATION CYTOLOGY, Non-Gynaec Cytology",
    vial: "In Lab only",
    price: 1199,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "second-opinion-108",
    category: "Cytology",
    name: "SECOND OPINION",
    vial: "",
    price: 499,
    reportingTime: "",
    sourcePage: 3,
  },
  {
    id: "culture-aerobic-susceptibility-pus-culture-109",
    category: "Bacteriology",
    name: "CULTURE AEROBIC & SUSCEPTIBILITY - PUS CULTURE",
    vial: "CONTAINER",
    price: 599,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "stool-culture-110",
    category: "Bacteriology",
    name: "STOOL CULTURE",
    vial: "CONTAINER",
    price: 599,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "pus-swab-culture-111",
    category: "Bacteriology",
    name: "PUS SWAB CULTURE",
    vial: "PUS",
    price: 599,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "throat-swab-culture-112",
    category: "Bacteriology",
    name: "THROAT SWAB CULTURE",
    vial: "SWAB",
    price: 599,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "conjunctival-swab-culture-113",
    category: "Bacteriology",
    name: "CONJUNCTIVAL SWAB CULTURE",
    vial: "SWAB",
    price: 599,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "skin-slit-smear-lepra-smear-114",
    category: "Bacteriology",
    name: "SKIN SLIT SMEAR - LEPRA SMEAR",
    vial: "In Lab only",
    price: 599,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "vaginal-swab-culsture-115",
    category: "Bacteriology",
    name: "VAGINAL SWAB CULSTURE",
    vial: "SWAB",
    price: 599,
    reportingTime: "48 Hrs",
    sourcePage: 3,
  },
  {
    id: "afb-stain-sputum-for-afb-116",
    category: "Bacteriology",
    name: "AFB STAIN - SPUTUM FOR AFB",
    vial: "SPUTUM",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 3,
  },
  {
    id: "afb-stain-sputum-for-afb-3-sample-117",
    category: "Bacteriology",
    name: "AFB STAIN - SPUTUM FOR AFB - 3 SAMPLE",
    vial: "SPUTUM",
    price: 599,
    reportingTime: "3 days",
    sourcePage: 3,
  },
  {
    id: "grams-stain-118",
    category: "Bacteriology",
    name: "GRAMS STAIN",
    vial: "",
    price: 199,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 3,
  },
  {
    id: "blood-culture-119",
    category: "Bacteriology",
    name: "BLOOD CULTURE",
    vial: "Sodium Heparin",
    price: 1199,
    reportingTime: "3 Days or 7 to 8 days",
    sourcePage: 3,
  },
  {
    id: "care-plus-advance-health-checkup-cbc-lft-lipid-profile-kft-sugar-f-r-hba1c-t3-t4-tsh-120",
    category: "Cytocare Profiles & Panels",
    name: "CARE PLUS - Advance Health Checkup (CBC, LFT, LIPID PROFILE, KFT, SUGAR F/R, HBA1C, T3 T4 TSH)",
    vial: "RED PURPLE GREY",
    price: 1499,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "fitness-plus-whole-body-checkup-cbc-esr-glucose-f-r-hba1c-kft-creatinine-urea-electrolyte-calcium-uric-acid-lft-lipid-profile-thyroid-profile-vit-d-vit-b12-total-protein-albumin-hbsag-ra-crp-urine-r-e-121",
    category: "Cytocare Profiles & Panels",
    name: "Fitness Plus - Whole Body Checkup = (CBC, ESR, GLUCOSE F/R, HBA1C, KFT (CREATININE, UREA, ELECTROLYTE, CALCIUM, URIC ACID), LFT, LIPID PROFILE, THYROID PROFILE, VIT D, VIT B12, TOTAL PROTEIN, ALBUMIN HBSAG, RA, CRP, URINE R/E)",
    vial: "RED BLACK PURPLE GREY, URINE",
    price: 2999,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "diabetics-monitor-fasting-pp-hba1c-urine-r-e-urine-microalbumin-albumin-creatinine-ratio-egfr-lipid-profile-creatinine-bun-uric-acid-tsh-122",
    category: "Cytocare Profiles & Panels",
    name: "DIABETICS MONITOR = (FASTING,PP,HBA1C,URINE R/E, URINE MICROALBUMIN & ALBUMIN CREATININE RATIO, eGFR, LIPID PROFILE,CREATININE, BUN, URIC ACID, TSH)",
    vial: "PURPLE GREY RED, URINE",
    price: 1499,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "diabetics-monitor-plus-fasting-pp-hba1c-urine-r-e-urine-microalbumin-albumin-creatinine-ratio-egfr-lipid-profile-creatinine-bun-uric-acid-tsh-homa-ir-insulin-resistance-index-123",
    category: "Cytocare Profiles & Panels",
    name: "DIABETICS MONITOR PLUS = (FASTING,PP,HBA1C, URINE R/E, URINE MICROALBUMIN & ALBUMIN CREATININE RATIO, eGFR, LIPID PROFILE,CREATININE, BUN, URIC ACID, TSH, HOMA IR : INSULIN RESISTANCE INDEX)",
    vial: "PURPLE GREY RED, URINE",
    price: 2999,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "iron-profile-iron-ferritin-total-iron-binding-capacity-tibc-transferrin-saturation-hemoglobin-hb-124",
    category: "Cytocare Profiles & Panels",
    name: "IRON Profile = (IRON, FERRITIN, Total Iron Binding Capacity (TIBC), Transferrin Saturation, Hemoglobin-HB )",
    vial: "RED, PURPLE",
    price: 1599,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 3,
  },
  {
    id: "fever-panel-cbc-esr-mp-widal-bilirubin-urine-r-e-125",
    category: "Cytocare Profiles & Panels",
    name: "FEVER PANEL = (CBC, ESR, MP, WIDAL, BILIRUBIN, URINE R/E)",
    vial: "RED BLACK PURPLE, URINE",
    price: 899,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 3,
  },
  {
    id: "anaemia-profile-1-cbc-peripheral-blood-smear-pbs-retic-count-hscrp-iron-profile-126",
    category: "Cytocare Profiles & Panels",
    name: "Anaemia Profile - 1 = (CBC, Peripheral Blood Smear-PBS, Retic Count, hsCRP, IRON Profile )",
    vial: "RED, PURPLE",
    price: 1599,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "anaemia-profile-2-cbc-peripheral-blood-smear-pbs-retic-count-hscrp-iron-profile-hb-electrophoresis-variant-patient-blood-transfusion-history-and-prescription-xerox-required-127",
    category: "Cytocare Profiles & Panels",
    name: "Anaemia Profile - 2 = (CBC, Peripheral Blood Smear-PBS, Retic Count, hsCRP, IRON Profile, HB Electrophoresis / Variant ) = (Patient Blood Transfusion History and Prescription Xerox required )",
    vial: "RED, PURPLE",
    price: 3999,
    reportingTime: "Next day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "arthrities-panel-1-cbc-esr-crp-uric-acid-aso-rf-calcium-128",
    category: "Cytocare Profiles & Panels",
    name: "ARTHRITIES PANEL - 1 (CBC, ESR, CRP, URIC ACID, ASO, RF, CALCIUM)",
    vial: "RED BLACK PURPLE",
    price: 1499,
    reportingTime: "Same day (6pm to 7pm)",
    sourcePage: 4,
  },
  {
    id: "arthrities-panel-2-cbc-esr-crp-uric-acid-aso-rf-calcium-ana-anti-ccp-129",
    category: "Cytocare Profiles & Panels",
    name: "ARTHRITIES PANEL - 2 (CBC, ESR, CRP, URIC ACID, ASO, RF, CALCIUM, ANA, ANTI CCP)",
    vial: "RED BLACK PURPLE",
    price: 2499,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "anc-profile-antenatal-profile-cbc-abo-sugar-vdrl-hiv-hbsag-hcv-tsh-urine-r-e-130",
    category: "Cytocare Profiles & Panels",
    name: "ANC PROFILE - ANTENATAL PROFILE = (CBC,ABO,SUGAR,VDRL,HIV,HBSAG,HCV,TSH,URINE R/E)",
    vial: "PURPLE GREY RED, URINE",
    price: 1299,
    reportingTime: "Same day",
    sourcePage: 4,
  },
  {
    id: "double-dual-marker-131",
    category: "Specialised Test Menu",
    name: "DOUBLE / DUAL MARKER",
    vial: "RED - PLAIN",
    price: 1799,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "pcod-panel-132",
    category: "Specialised Test Menu",
    name: "PCOD PANEL",
    vial: "RED - PLAIN",
    price: 3399,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "torch-10-panel-133",
    category: "Specialised Test Menu",
    name: "TORCH 10 PANEL",
    vial: "RED - PLAIN",
    price: 2499,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "ca-125-cancer-marker-serum-134",
    category: "Specialised Test Menu",
    name: "CA 125, CANCER MARKER, SERUM",
    vial: "RED - PLAIN",
    price: 999,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "amh-anti-mullerian-hormone-serum-135",
    category: "Specialised Test Menu",
    name: "AMH (ANTI MULLERIAN HORMONE), SERUM",
    vial: "RED - PLAIN",
    price: 1999,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "hb-electrophrosis-hplc-136",
    category: "Specialised Test Menu",
    name: "HB ELECTROPHROSIS / HPLC",
    vial: "PURPLE - EDTA",
    price: 1099,
    reportingTime: "Next day (6pm to 7:30pm)",
    sourcePage: 4,
  },
  {
    id: "homa-ir-1st-trimester-fasting-sample-137",
    category: "Specialised Test Menu",
    name: "HOMA IR (1st Trimester) - Fasting Sample",
    vial: "RED - PLAIN, GRAY",
    price: 1199,
    reportingTime: "Same day (6pm to 7:30pm)",
    sourcePage: 4,
  },
];

export const cytocareCategories = Array.from(
  new Set(cytocareTests.map((test) => test.category))
);